name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

  deploy:
    needs: [test]
    if: github.ref_name == 'main'
    uses: ./.github/workflows/deploy.yml
    concurrency:
      group: deploy-${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: false
    secrets: inherit
